import TodoDashboard from '@/components/TodoDashboard'
import Head from 'next/head'


const Home : React.FC = ()=> {
  return (
    <>
      <Head>
        <title>TodoApp-tsc-njs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
            {/* <!-- Font family added --> */}
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');
        </style>
      </Head>
      <div
        className='w-full h-screen bg-pink flex items-center justify-center font-lato'
      >
        <TodoDashboard/>
      </div>
    </>
  )
}

export default Home;
